version: '3.9'

services:
      client:
        build: ./client
        container_name: react_container
        restart: always
        ports:
          - 3000:3000
        stdin_open: true
        tty: true  

      server:
        build: ./server
        container_name: express_container
        ports:
          - 5000:5000
        restart: always
